export type technology = {
  id: number;
  type: string;
  language: string;
  description: string;
  status: string;
  owner: string;
  createdAt: string;
  updatedAt: string;
};

const technologies: technology[] = [
  {
    id: 0,
    type: "language",
    language: "JavaScript",
    description:
      "A high-level, versatile programming language commonly used for web development.",
    status: "Active",
    owner: "ECMA International",
    createdAt: "1995-12-04",
    updatedAt: "2024-06-09",
  },
  {
    id: 1,
    type: "language",
    language: "TypeScript",
    description:
      "A strongly typed programming language that builds on JavaScript, giving you better tooling at any scale.",
    status: "Active",
    owner: "Microsoft",
    createdAt: "2012-10-01",
    updatedAt: "2024-06-09",
  },
  {
    id: 2,
    type: "language",
    language: "Solidity",
    description:
      "A high-level programming language for writing smart contracts",
    status: "Active",
    owner: "Solidity Labs",
    createdAt: "2014-08-07",
    updatedAt: "2024-05-21",
  },
  {
    id: 3,
    type: "language",
    language: "HTML",
    description:
      "Hypertext Markup Language used for creating web pages and web applications",
    status: "Active",
    owner: "WHATWG",
    createdAt: "2008-01-22",
    updatedAt: "2008-01-22",
  },
  {
    id: 4,
    type: "language",
    language: "CSS",
    description:
      "Cascading Style Sheets used for styling web pages and web applications",
    status: "Active",
    owner: "W3C",
    createdAt: "1996-12-17",
    updatedAt: "2020-12-07",
  },
  {
    id: 5,
    type: "library",
    language: "React.js",
    description: "A JavaScript library used to build user interfaces",
    status: "Active",
    owner: "Facebook",
    createdAt: "2013-05-29",
    updatedAt: "2024-04-26",
  },
  {
    id: 6,
    type: "library",
    language: "Tailwind CSS",
    description:
      "A utility-first CSS framework to build custom designs without writing CSS",
    status: "Active",
    owner: "Tailwind Labs",
    createdAt: "2017-11-01",
    updatedAt: "2024-06-05",
  },
  {
    id: 7,
    type: "library",
    language: "Puppeteer",
    description: "A Node.js library to control headless Chrome or Chromium",
    status: "Active",
    owner: "Google",
    createdAt: "2017-08-24",
    updatedAt: "2024-05-24",
  },
  {
    id: 8,
    type: "framework",
    language: "Next.js",
    description:
      "A React framework to build server-side rendered and static web applications",
    status: "Active",
    owner: "Vercel",
    createdAt: "2016-11-04",
    updatedAt: "2024-06-08",
  },
  {
    id: 9,
    type: "cloud",
    language: "Supabase",
    description:
      "An open-source Firebase alternative with PostgreSQL database, authentication, and storage",
    status: "Active",
    owner: "Supabase",
    createdAt: "2020-01-01",
    updatedAt: "2024-06-09",
  },
  {
    id: 10,
    type: "cloud",
    language: "Firebase",
    description:
      "A platform developed by Google for building mobile and web applications",
    status: "Active",
    owner: "Google",
    createdAt: "2012-01-01",
    updatedAt: "2024-06-09",
  },
  {
    id: 11,
    type: "database",
    language: "MySQL",
    description: "An open-source relational database management system",
    status: "Active",
    owner: "Oracle",
    createdAt: "1995-05-23",
    updatedAt: "2024-04-10",
  },
  {
    id: 12,
    type: "database",
    language: "PostgreSQL",
    description: "An open-source object-relational database management system",
    status: "Active",
    owner: "OS Community",
    createdAt: "1996-07-08",
    updatedAt: "2024-05-09",
  },
  {
    id: 13,
    type: "runtime",
    language: "Node.js",
    description:
      "A JavaScript runtime environment built on Chrome's V8 JavaScript engine",
    status: "Active",
    owner: "OpenJS Foundation",
    createdAt: "2009-05-27",
    updatedAt: "2024-05-15",
  },
  {
    id: 14,
    type: "framework",
    language: "Express.js",
    description: "A minimalist web framework for Node.js",
    status: "Active",
    owner: "StrongLoop",
    createdAt: "2010-05-22",
    updatedAt: "2024-03-25",
  },
  {
    id: 15,
    type: "framework",
    language: "Thirdweb",
    description: "A platform for developing decentralized web applications",
    status: "Active",
    owner: "Thirdweb",
    createdAt: "2022-08-29",
    updatedAt: "2024-06-04",
  },
  {
    id: 16,
    type: "framework",
    language: "NestJS",
    description: "A progressive Node.js framework for building server-side applications",
    status: "Active",
    owner: "Kamil Mysliwiec",
    createdAt: "2017-10-05",
    updatedAt: "2026-02-19",
  },
  {
    id: 17,
    type: "library",
    language: "Prisma",
    description: "A next-generation ORM for Node.js and TypeScript",
    status: "Active",
    owner: "Prisma",
    createdAt: "2019-06-18",
    updatedAt: "2026-03-12",
  },
  {
    id: 18,
    type: "library",
    language: "Socket.io",
    description: "A library for real-time bidirectional event-based communication",
    status: "Active",
    owner: "Socket.io",
    createdAt: "2010-03-19",
    updatedAt: "2025-11-07",
  },
  {
    id: 19,
    type: "cloud",
    language: "AWS",
    description: "Cloud computing platform with EC2, ECS, S3 and other infrastructure services",
    status: "Active",
    owner: "Amazon",
    createdAt: "2006-03-14",
    updatedAt: "2026-03-01",
  },
  {
    id: 20,
    type: "database",
    language: "Redis",
    description: "An in-memory data store used as a database, cache, and message broker",
    status: "Active",
    owner: "Redis Ltd.",
    createdAt: "2009-05-10",
    updatedAt: "2025-10-22",
  },
  {
    id: 21,
    type: "library",
    language: "Stripe",
    description: "A payment processing platform and API for online businesses",
    status: "Active",
    owner: "Stripe",
    createdAt: "2011-09-29",
    updatedAt: "2026-02-05",
  },
];

export { technologies };
